export const FETCH_INVESTMENTS_DATA = 'FETCH_INVESTMENTS_DATA'
export const SET_INVESTMENTS_DATA = 'SET_INVESTMENTS_DATA'
export const SET_MONTHS_IN_PAST_BY_INDEX = 'SET_MONTHS_IN_PAST_BY_INDEX'
export const SET_INVESTMENTS_CHART_DATA = 'SET_INVESTMENTS_CHART_DATA'
